version: '3'

services:
  automealer:
    build: .
    image: automealer:latest
    ports:
      - "6666:6666"
    environment:
      - PORT=6666
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
